# Generated by Django 4.0.5 on 2022-07-16 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceSymbolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CoinList',
            fields=[
                ('coin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100, null=True)),
                ('api_secret', models.CharField(max_length=100, null=True)),
                ('SECRET_KEY', models.CharField(max_length=100, null=True)),
                ('mysql_host', models.GenericIPAddressField(null=True)),
                ('mysql_db_name', models.CharField(max_length=100, null=True)),
                ('mysql_user', models.CharField(max_length=100, null=True)),
                ('mysql_pwd', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=15)),
                ('spot_balance', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('usdtbal', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('btcbal', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('usdtspot', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('btcspot', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('usdtsav', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('btcsav', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('usdtstake', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('btcstake', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAssetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('asset', models.CharField(max_length=15)),
                ('free', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('locked', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('ownusdt', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('ownbtc', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Ohlcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('open', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('high', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('low', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('close', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('num_trades', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('taker_base_vol', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('taker_quote_vol', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.coinlist')),
            ],
        ),
    ]
