# Generated by Django 4.0.3 on 2022-04-24 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceSymbolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CoinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('totalbids', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('totalasks', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('slug', models.SlugField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=15)),
                ('spot_balance', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('savings_balance', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('staking_balance', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAssetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=15)),
                ('free', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('locked', models.DecimalField(decimal_places=18, default=0.0, max_digits=36)),
                ('own_usdt', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('own_btc', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
            ],
        ),
    ]
