# Generated by Django 4.0.5 on 2022-06-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlcv',
            name='coin',
        ),
    ]
