# Generated by Django 4.0.3 on 2022-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletassetlist',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
