# Generated by Django 4.0.5 on 2022-06-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_squashed_0017_remove_ohlcv_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohlcv',
            old_name='numtrades',
            new_name='num_trades',
        ),
        migrations.RenameField(
            model_name='ohlcv',
            old_name='takerbasevol',
            new_name='taker_base_vol',
        ),
        migrations.RenameField(
            model_name='ohlcv',
            old_name='takerquotevol',
            new_name='taker_quote_vol',
        ),
    ]
