# Generated by Django 4.0.5 on 2022-06-23 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_numtrades_ohlcv_num_trades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlcv',
            name='id',
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
