# Generated by Django 4.0.5 on 2022-06-23 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_ohlcv_id_alter_ohlcv_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinlist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='walletassetbalance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='walletassetlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='coinlist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walletassetbalance',
            name='time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='walletassetlist',
            name='time',
            field=models.TimeField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
