# Generated by Django 4.0.3 on 2022-04-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_walletassetbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletAssetBalance',
        ),
    ]
