# Generated by Django 4.0.3 on 2022-04-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_own_btc_walletassetlist_ownbtc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('usdtblance', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
                ('btcbalance', models.DecimalField(decimal_places=8, default=0.0, max_digits=19)),
            ],
        ),
    ]
