# Generated by Django 4.0.5 on 2022-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_coinlist_price_remove_coinlist_totalasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlcv',
            name='coin',
        ),
        migrations.AddField(
            model_name='coinlist',
            name='price',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='totalasks',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='totalbids',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='cryptobotsettings',
            name='mysql_db_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cryptobotsettings',
            name='mysql_host',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='cryptobotsettings',
            name='mysql_pwd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cryptobotsettings',
            name='mysql_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cryptobotsettings',
            name='SECRET_KEY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cryptobotsettings',
            name='api_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cryptobotsettings',
            name='api_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
