# Generated by Django 4.0.5 on 2022-06-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_ohlcv_coin_coinlist_price_coinlist_totalasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='totalasks',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='totalbids',
        ),
    ]
