# Generated by Django 4.0.4 on 2022-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_usdtblance_walletassetbalance_usdtbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletassetbalance',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
