# Generated by Django 4.0.5 on 2022-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_coinlist_price_remove_coinlist_totalasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinlist',
            name='date',
        ),
        migrations.AlterField(
            model_name='coinlist',
            name='coin',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
