# Generated by Django 4.0.5 on 2022-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_ohlcv_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletassetbalance',
            old_name='btcbalance',
            new_name='btcbal',
        ),
        migrations.RenameField(
            model_name='walletassetbalance',
            old_name='usdtbalance',
            new_name='btcsav',
        ),
        migrations.AddField(
            model_name='walletassetbalance',
            name='btcspot',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='walletassetbalance',
            name='btcstake',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='walletassetbalance',
            name='usdtbal',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='walletassetbalance',
            name='usdtsav',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='walletassetbalance',
            name='usdtspot',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='walletassetbalance',
            name='usdtstake',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=19),
        ),
    ]
