# Generated by Django 4.0.4 on 2022-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_wallet_savings_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret', models.CharField(max_length=100)),
                ('SECRET_KEY', models.CharField(max_length=100)),
            ],
        ),
    ]
