# Generated by Django 4.0.4 on 2022-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_coinlist_price_alter_coinlist_totalasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinlist',
            name='price',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=36),
        ),
        migrations.AlterField(
            model_name='coinlist',
            name='totalasks',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=36),
        ),
        migrations.AlterField(
            model_name='coinlist',
            name='totalbids',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=36),
        ),
    ]
