# Generated by Django 4.0.4 on 2022-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_coinlist_price_alter_coinlist_totalasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinlist',
            name='close',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='high',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='low',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='open',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='volume',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
    ]
