# Generated by Django 4.0.4 on 2022-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_coinlist_close_coinlist_high_coinlist_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinlist',
            name='numtrades',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='takerbasevol',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='coinlist',
            name='takerquotevol',
            field=models.DecimalField(decimal_places=18, max_digits=36, null=True),
        ),
    ]
