# Generated by Django 4.0.4 on 2022-06-09 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_coinlist_numtrades_coinlist_takerbasevol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ohlcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('open', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('high', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('low', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('close', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('numtrades', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('takerbasevol', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('takerquotevol', models.DecimalField(decimal_places=18, max_digits=36, null=True)),
                ('slug', models.SlugField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='close',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='high',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='low',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='numtrades',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='open',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='takerbasevol',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='takerquotevol',
        ),
        migrations.RemoveField(
            model_name='coinlist',
            name='volume',
        ),
    ]
