# Generated by Django 4.0.4 on 2022-06-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_ohlcv_remove_coinlist_close_remove_coinlist_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohlcv',
            name='slug',
        ),
    ]
